### ISSUE TITLE
RebelController vs Controller

### ISSUE THREAD

**Issue by yuriuss** [codeborne/play-rebel#2]
Hi!

Help me please. I want to understand why I should use a RebelController instead of a Controller (classic play) class? Does it depend on tests (static is not good)? 
And how I should make tests for POST requests? I didn't find examples in play-rebel/test/playmvc directory.

Thank you!

**Comment by asolntsev** [comment]
@yuriuss Hi. 
`play.mvc.Controller` has all static fields (`request`, `response` etc) and methods (`renderTemplate`, `template` etc). It causes bad design. Such controllers are hard to test.

`RebelController` has non-static fields and methods. They are easy to mock and test.

We usually write UNIT tests for our code. You just create an instance of your controller and call the desired method. No need to execute POST or GET requests.

P.S. We also write UI tests (which is a higher level integration tests).
