### ISSUE TITLE
Application.index action not found

### ISSUE THREAD

**Issue by yuriuss** [codeborne/play-rebel#3]
Hi!

I created the application (play new test1), then registered the dependencies, changed the Application.java and launched the program (play run) and then I got an exception:

> ~ play! 1.5.x-1.5.3-4-g61498dc, https://www.playframework.com
> ~ Ctrl+C to stop
> ~ using java version "1.8.0_201"
> Listening for transport dt_socket at address: 8000
> 09:24:52,074 INFO  ~ Starting /home/yuriuss/test1
> :: loading settings :: url = jar:file:/home/yuriuss/play/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
> 09:24:52,280 INFO  ~ REBEL: Play enhancers disabled
> 09:24:52,280 INFO  ~ REBEL: Play compilation also disabled
> 09:24:52,292 WARN  ~ You're running Play! in DEV mode
> 09:24:52,347 INFO  ~ Listening for HTTP on port 9000 (Waiting a first request to start) ...
> ~ Server is up and running
> 09:24:59,845 INFO  ~ REBEL: Play compilation disabled
> 09:24:59,908 INFO  ~ Application 'test1' is now started !
> 09:24:59,908 INFO  ~ Congratulations! No legacy redirects are used in your project.
> 09:24:59,911 ERROR ~ 
> 
> @7cnbomk6b
> Application.index action not found
> 
> Action not found
> Action Application.index could not be found. Error raised is Controller controllers.Application not found
> 
> play.exceptions.ActionNotFoundException: Action Application.index not found
> 	at play.mvc.ActionInvoker.getActionMethod(ActionInvoker.java:588)
> 	at play.mvc.ActionInvoker.resolve(ActionInvoker.java:74)
> 	at Invocation.HTTP Request(Play!)
> Caused by: java.lang.Exception: Controller controllers.Application not found
> 	... 3 more

Here is the code:
**$ ~/test1/app/controllers/Application.java**
> package controllers;
> 
> import play.mvc.Redirector;
> import play.rebel.RebelController;
> 
> public class Application extends RebelController {
>     protected static Redirector redirect = new Redirector();
>     public void index() {
>         redirect.to("/");
>     }
> }
> 

**$ ~/test1/conf/dependencies.yml**
> require:
>     - play 1.5.+
>     - play-codeborne-jar -> rebel 1.3
>     - org.assertj -> assertj-core 3.8.0
>     - org.mockito -> mockito-core 2.11.0
>     - com.google.guava -> guava 23.0

**$ ~/test1/conf/play.plugins**
> 0:play.rebel.PlayRebelAntiEnhancerPlugin
> 2000:play.rebel.migration.LegacyRedirectsDetector

**$ ~/test1/conf/routes**
> GET     /                                       Application.index
> GET     /favicon.ico                            404
> GET     /public/                                staticDir:public
> *       /{controller}/{action}                  {controller}.{action}

Any ideas? 
Thanks.

**Comment by angryziber** [comment]
Play Rebel is a stripped-down version of Play framework - the main difference is that you need to compile everything by a build tool before launching, no compilation will take place at runtime
